/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AttachField: typeof import('./src/components/fields/AttachField.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Check: typeof import('./src/components/Check.vue')['default']
    CheckField: typeof import('./src/components/fields/CheckField.vue')['default']
    ChildTableEditor: typeof import('./src/components/ChildTableEditor.vue')['default']
    ChildTableField: typeof import('./src/components/fields/ChildTableField.vue')['default']
    ColorField: typeof import('./src/components/fields/ColorField.vue')['default']
    CommandDialog: typeof import('./src/components/CommandDialog.vue')['default']
    DateField: typeof import('./src/components/fields/DateField.vue')['default']
    DateTimeField: typeof import('./src/components/fields/DateTimeField.vue')['default']
    FloatField: typeof import('./src/components/fields/FloatField.vue')['default']
    HeadingField: typeof import('./src/components/fields/HeadingField.vue')['default']
    IntField: typeof import('./src/components/fields/IntField.vue')['default']
    LinkField: typeof import('./src/components/fields/LinkField.vue')['default']
    ListView: typeof import('./src/components/list/ListView.vue')['default']
    LocalsDemoComponent: typeof import('./src/components/LocalsDemoComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionBreakField: typeof import('./src/components/fields/SectionBreakField.vue')['default']
    SelectField: typeof import('./src/components/fields/SelectField.vue')['default']
    TextAreaField: typeof import('./src/components/fields/TextAreaField.vue')['default']
    TextField: typeof import('./src/components/fields/TextField.vue')['default']
    TimeField: typeof import('./src/components/fields/TimeField.vue')['default']
  }
}
